[tool.isort]

multi_line_output      = 3
include_trailing_comma = true
force_grid_wrap        = 0
use_parentheses        = true
line_length            = 88
known_third_party      = "pytest"
known_first_party      = "Pegasus"
forced_separate        = "Pegasus"
skip                   = "Pegasus/cli"


[tool.black]

target-version = ["py27"]

exclude       = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | Pegasus/cli
)/
'''


[build-system]

requires      = ["setuptools>=44.0.0", "wheel"]
build-backend = "setuptools.build_meta"
